#ifndef GUI_ICONS
#define GUI_ICONS
#include "TFT.h"

const uint16_t TRANSPARENT_ICON[16][16] = {
    {TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT},
};

const uint16_t PLAY_ICON[16][16] = {
    {TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, TRANSPARENT, TRANSPARENT, GREEN, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, TRANSPARENT, TRANSPARENT, GREEN, GREEN, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, TRANSPARENT, TRANSPARENT, GREEN, GREEN, GREEN, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, TRANSPARENT, TRANSPARENT, GREEN, GREEN, GREEN, GREEN, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, TRANSPARENT, TRANSPARENT, GREEN, GREEN, GREEN, GREEN, GREEN, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, TRANSPARENT, TRANSPARENT, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, TRANSPARENT, TRANSPARENT, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, TRANSPARENT, TRANSPARENT, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, TRANSPARENT, TRANSPARENT, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, TRANSPARENT, TRANSPARENT, GREEN, GREEN, GREEN, GREEN, GREEN, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, TRANSPARENT, TRANSPARENT, GREEN, GREEN, GREEN, GREEN, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, TRANSPARENT, TRANSPARENT, GREEN, GREEN, GREEN, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, TRANSPARENT, TRANSPARENT, GREEN, GREEN, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, TRANSPARENT, TRANSPARENT, GREEN, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT},
};

#define CAMERA_COLOR 35990

const uint16_t CAMERA_ICON[16][16] = {
    {TRANSPARENT, TRANSPARENT, TRANSPARENT, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, TRANSPARENT, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, CAMERA_COLOR, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, CAMERA_COLOR, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, TRANSPARENT, TRANSPARENT, TRANSPARENT, CAMERA_COLOR, CAMERA_COLOR, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, TRANSPARENT, TRANSPARENT, TRANSPARENT, CAMERA_COLOR, CAMERA_COLOR, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, TRANSPARENT, TRANSPARENT, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, TRANSPARENT, TRANSPARENT, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, TRANSPARENT, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, TRANSPARENT, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, TRANSPARENT, TRANSPARENT, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, TRANSPARENT, TRANSPARENT, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, TRANSPARENT, TRANSPARENT, TRANSPARENT, CAMERA_COLOR, CAMERA_COLOR, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, TRANSPARENT, TRANSPARENT, TRANSPARENT, CAMERA_COLOR, CAMERA_COLOR, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, CAMERA_COLOR, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, TRANSPARENT, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, CAMERA_COLOR, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, CAMERA_COLOR, TRANSPARENT, TRANSPARENT},
    {TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT, TRANSPARENT}
};

#endif